// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvfhfyaltuejonkjnfsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZmhmeWFsdHVlam9ua2puZnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDU4MTAsImV4cCI6MjA2NDMyMTgxMH0.AbkiiCY1QJU8faFYzxJyLmUQAItAg2WIICbqI1AYTBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);